<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <CLSCompliant>true</CLSCompliant>
  </PropertyGroup>

  <ItemGroup Label="Analyzers" Condition="$(MSBuildProjectName) != ''">
    <PackageReference Include="Roslynator.Analyzers"               Version="4.15.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.100" PrivateAssets="all" />
  </ItemGroup>
</Project>
