<Project>
  <PropertyGroup>
    <!-- Needed for proper nullable handling -->
    <Nullable>enable</Nullable>

    <!-- Treat warnings as errors -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- File-scoped namespaces -->
    <LangVersion>latest</LangVersion>

    <!-- Common output paths -->
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <!-- Determinitive builds -->
    <Deterministic>true</Deterministic>

    <!-- CenterCLS compliance -->
    <CLSCompliant>true</CLSCompliant>
  </PropertyGroup>

  <!-- Add analyzers -->
  <ItemGroup Label="Analyzers" Condition="$(MSBuildProjectName) != ''">
    <PackageReference Include="Roslynator.Analyzers"               Version="4.15.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.100" PrivateAssets="all" />
  </ItemGroup>
</Project>
